TOPICS = [
    {
        "id": "python-basics",
        "track": "Python Core",
        "title": "Python Basics",
        "level": "Beginner",
        "intro": "Python basics are the foundation for every other interview topic. You should be able to read a small script, predict what each line does, explain the data type of each value, and fix simple syntax or indentation errors. Do not memorize only keywords; learn the flow of execution: Python starts at the top, creates names, evaluates expressions, enters branches, repeats loops, and calls functions when asked.",
        "mental_model": "A Python program is a sequence of statements. Variables are names pointing to objects. Expressions produce values. Indentation defines blocks. Conditions choose a path. Loops repeat work. Functions package a reusable idea.",
        "syntax": "name = 'Asha'\nage = 24\nscore = 82.5\nis_ready = True\n\nif score >= 60:\n    result = 'pass'\nelse:\n    result = 'retry'\n\nfor number in [1, 2, 3]:\n    print(number)\n\nwhile age < 30:\n    age += 1",
        "example": "def interview_status(score):\n    if score >= 80:\n        return 'strong'\n    if score >= 60:\n        return 'practice more'\n    return 'restart basics'\n\nprint(interview_status(72))",
        "must_know": [
            "Common data types: `int`, `float`, `str`, `bool`, `list`, `dict`, `set`, `tuple`, and `None`.",
            "Assignment binds a name to an object; it does not permanently attach a type to the variable name.",
            "Indentation is part of Python syntax. A missing colon or wrong indent can change or break the program.",
            "`==` checks value equality. `is` checks whether two names refer to the exact same object.",
            "Truthy and falsy values matter: empty strings, empty collections, zero, and `None` behave as false in conditions.",
        ],
        "common_traps": [
            "Using `=` when you meant `==` in an explanation.",
            "Comparing strings and numbers without converting first.",
            "Forgetting that input from users is usually text.",
            "Trying to read a variable before it is assigned.",
        ],
        "interview": [
            "Explain mutable vs immutable values.",
            "Know the difference between `is` and `==`.",
            "Be able to trace a loop without running it.",
            "Practice saying why a value is truthy or falsy.",
        ],
        "docs": [
            {"label": "Python Tutorial: An Informal Introduction", "url": "https://docs.python.org/3/tutorial/introduction.html"},
            {"label": "Python Tutorial: Control Flow Tools", "url": "https://docs.python.org/3/tutorial/controlflow.html"},
        ],
    },
    {
        "id": "data-structures",
        "track": "Python Core",
        "title": "Lists, Dicts, Sets, Tuples",
        "level": "Beginner",
        "intro": "Most beginner coding interviews are data-structure interviews in disguise. The interviewer wants to see whether you choose a list for ordered items, a dictionary for lookup or counting, a set for uniqueness and membership, and a tuple for fixed grouped data. Your answer should mention both behavior and why that container fits the task.",
        "mental_model": "Choose the container by the question you need to answer. Ordered sequence? Use a list. Key to value? Use a dict. Already seen this item? Use a set. Fixed record? Use a tuple.",
        "syntax": "items = [10, 20, 30]\nitems.append(40)\n\nuser = {'name': 'Ravi', 'role': 'SRE'}\nrole = user.get('role', 'unknown')\n\nunique_ids = {101, 102, 101}\npoint = (10, 20)",
        "example": "def first_duplicate(items):\n    seen = set()\n    for item in items:\n        if item in seen:\n            return item\n        seen.add(item)\n    return None",
        "must_know": [
            "Lists preserve order and are good for iteration, appending, sorting, and slicing.",
            "Dicts map keys to values and are the standard tool for frequency counting.",
            "Sets remove duplicates and make membership checks easy.",
            "Tuples are immutable and useful for fixed pairs like coordinates or `(status, message)`.",
            "Dict and set membership are usually much faster than scanning a list for large inputs.",
        ],
        "common_traps": [
            "Using a list for repeated membership checks when a set would be clearer.",
            "Changing a list while looping over it without understanding the effect.",
            "Forgetting that dict keys must be hashable.",
            "Assuming set order is a stable business rule.",
        ],
        "interview": [
            "Use a dict for frequency counting.",
            "Use a set for membership checks.",
            "Mention average O(1) lookup for dicts and sets.",
            "Explain why you chose one container over another.",
        ],
        "docs": [
            {"label": "Python Tutorial: Data Structures", "url": "https://docs.python.org/3/tutorial/datastructures.html"},
        ],
    },
    {
        "id": "functions",
        "track": "Python Core",
        "title": "Functions and Clean Code",
        "level": "Beginner",
        "intro": "Functions are how you make a solution testable and explainable. In interviews, a function shows the input, the output, and the boundaries of your idea. A good beginner answer is not clever; it is small, named clearly, and easy to test with two or three examples.",
        "mental_model": "A function is a named mini-program. It receives inputs as parameters, does work, and usually returns a result. Good functions have one clear purpose.",
        "syntax": "def add(a, b=0):\n    return a + b\n\nresult = add(2, 3)\nresult_again = add(a=2, b=3)",
        "example": "def normalize_name(name):\n    cleaned = name.strip()\n    return cleaned.title()\n\nassert normalize_name('  ada lovelace ') == 'Ada Lovelace'",
        "must_know": [
            "Parameters are names inside the function; arguments are the actual values passed in.",
            "`return` sends a value back to the caller. `print` only displays text.",
            "Default arguments are useful, but mutable defaults like `[]` can surprise beginners.",
            "Small functions are easier to test, debug, and explain.",
            "Type hints help readers understand expected inputs and outputs, even though Python remains dynamic.",
        ],
        "common_traps": [
            "Printing the answer instead of returning it.",
            "Doing too many unrelated things in one function.",
            "Using unclear names like `x`, `temp`, and `data` everywhere.",
            "Using a mutable default argument without understanding shared state.",
        ],
        "interview": [
            "Explain positional vs keyword arguments.",
            "Avoid hidden global state.",
            "Return values instead of only printing.",
            "Describe your function contract: input, behavior, output.",
        ],
        "docs": [
            {"label": "Python Tutorial: Defining Functions", "url": "https://docs.python.org/3/tutorial/controlflow.html#defining-functions"},
            {"label": "Python Docs: Typing", "url": "https://docs.python.org/3/library/typing.html"},
        ],
    },
    {
        "id": "oop",
        "track": "Python Core",
        "title": "OOP",
        "level": "Intermediate",
        "intro": "Object-oriented programming groups state and behavior into classes. For interviews, you do not need to over-engineer everything into objects, but you should understand how a class creates instances, how methods receive `self`, and when an object makes the code clearer than passing dictionaries around.",
        "mental_model": "A class is a blueprint. An instance is one object built from that blueprint. Attributes store data on the instance. Methods are functions that operate on that instance.",
        "syntax": "class User:\n    def __init__(self, name):\n        self.name = name\n\n    def greet(self):\n        return f'Hi {self.name}'\n\nuser = User('Mina')\nprint(user.greet())",
        "example": "class RetryPolicy:\n    def __init__(self, max_attempts):\n        self.max_attempts = max_attempts\n\n    def should_retry(self, attempt_number):\n        return attempt_number < self.max_attempts",
        "must_know": [
            "`__init__` initializes a new instance.",
            "`self` is the current instance. It lets a method access that object's attributes.",
            "Inheritance reuses behavior from a parent class, but composition is often simpler.",
            "Dataclasses are useful when a class mainly stores data.",
            "Avoid creating classes when one simple function is enough.",
        ],
        "common_traps": [
            "Forgetting `self` in method definitions.",
            "Putting instance-specific data on the class by mistake.",
            "Using inheritance only to avoid writing a few lines.",
            "Making objects before you understand the data and behavior.",
        ],
        "interview": [
            "Explain `self` clearly.",
            "Know composition vs inheritance.",
            "Mention dataclasses for plain data objects.",
            "Be ready to model a simple real-world object.",
        ],
        "docs": [
            {"label": "Python Tutorial: Classes", "url": "https://docs.python.org/3/tutorial/classes.html"},
            {"label": "Python Docs: dataclasses", "url": "https://docs.python.org/3/library/dataclasses.html"},
        ],
    },
    {
        "id": "errors-testing",
        "track": "Engineering Habits",
        "title": "Errors, Debugging, and Testing",
        "level": "Beginner",
        "intro": "Strong candidates do not panic when code fails. They read the traceback, identify the failing line, form a small hypothesis, and test one change. Learn exceptions, assertions, unit tests, and edge cases because interviews often reward your debugging process as much as the final answer.",
        "mental_model": "An exception is Python saying it cannot continue normally. A test is a repeatable check that protects expected behavior. Debugging is narrowing the distance between what you expected and what happened.",
        "syntax": "try:\n    value = int(text)\nexcept ValueError:\n    value = 0\n\nassert value >= 0",
        "example": "def safe_divide(a, b):\n    if b == 0:\n        return None\n    return a / b\n\nassert safe_divide(10, 2) == 5\nassert safe_divide(10, 0) is None",
        "must_know": [
            "Read the last traceback line first to identify the exception type.",
            "Catch specific exceptions such as `ValueError`, not every possible error.",
            "Test normal cases and edge cases: empty input, duplicates, zero, negative numbers, and `None`.",
            "Use assertions or unit tests to make your expectation explicit.",
            "A good debugging explanation is step by step, not random guessing.",
        ],
        "common_traps": [
            "Using bare `except` and hiding real bugs.",
            "Testing only the happy path.",
            "Changing many things at once while debugging.",
            "Ignoring the exact line number in the traceback.",
        ],
        "interview": [
            "Do not hide errors with bare `except`.",
            "Explain what you would test first.",
            "Use edge cases: empty input, duplicates, zero, None.",
            "Say how you would reproduce the bug.",
        ],
        "docs": [
            {"label": "Python Tutorial: Errors and Exceptions", "url": "https://docs.python.org/3/tutorial/errors.html"},
            {"label": "Python Docs: unittest", "url": "https://docs.python.org/3/library/unittest.html"},
        ],
    },
    {
        "id": "fastapi",
        "track": "Backend",
        "title": "FastAPI",
        "level": "Intermediate",
        "intro": "FastAPI is used to build HTTP APIs with Python type hints. For interviews, focus on route handlers, request bodies, response models, dependency injection, validation, status codes, and how an API should fail cleanly. The important skill is not only writing `@app.get`; it is explaining the request lifecycle.",
        "mental_model": "A client sends an HTTP request. FastAPI matches the path and method, validates input with Python types and Pydantic models, calls your route function, then serializes the response.",
        "syntax": "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass UserCreate(BaseModel):\n    name: str\n    email: str\n\n@app.post('/users', status_code=201)\ndef create_user(user: UserCreate):\n    return {'message': 'created', 'user': user}",
        "example": "Keep route handlers thin. Validate input at the boundary, call a service function for business logic, and return clear status codes and response shapes.",
        "must_know": [
            "HTTP methods communicate intent: GET reads, POST creates, PUT/PATCH updates, DELETE removes.",
            "Pydantic models describe and validate request and response data.",
            "FastAPI automatically generates OpenAPI documentation for routes.",
            "Use dependencies for shared concerns like authentication, database sessions, and configuration.",
            "Async routes help when awaiting async I/O. CPU-heavy work needs a different strategy.",
        ],
        "common_traps": [
            "Returning inconsistent response shapes.",
            "Using HTTP 200 for every outcome.",
            "Blocking inside async routes with sync network or database calls.",
            "Putting all business logic inside the route function.",
        ],
        "interview": [
            "Know GET vs POST vs PUT/PATCH vs DELETE.",
            "Explain validation with Pydantic.",
            "Mention async routes only help when doing async I/O.",
            "Explain how you would debug a 422 validation error.",
        ],
        "docs": [
            {"label": "FastAPI Tutorial", "url": "https://fastapi.tiangolo.com/tutorial/"},
            {"label": "FastAPI: Body - Multiple Parameters", "url": "https://fastapi.tiangolo.com/tutorial/body-multiple-params/"},
        ],
    },
    {
        "id": "pydantic",
        "track": "Backend",
        "title": "Pydantic",
        "level": "Intermediate",
        "intro": "Pydantic turns untrusted data into validated Python objects. It is common in FastAPI, configuration, API clients, and AI app boundaries. In an interview, frame Pydantic as a boundary tool: outside data is messy, and models make assumptions explicit.",
        "mental_model": "A Pydantic model is a typed contract. Input data is parsed and validated into a Python object. Output can then be serialized back into dictionaries or JSON.",
        "syntax": "from pydantic import BaseModel, Field\n\nclass Ticket(BaseModel):\n    id: int\n    title: str\n    priority: int = Field(ge=1, le=5)\n\npayload = {'id': '123', 'title': 'Disk full', 'priority': 2}\nticket = Ticket.model_validate(payload)",
        "example": "Use Pydantic when data crosses a boundary: HTTP request body, environment config, LLM structured output, message payload, or database-facing DTO.",
        "must_know": [
            "Validation checks whether data matches expected types and rules.",
            "Serialization converts models into transport-friendly forms such as dict or JSON.",
            "Defaults make fields optional only when a sensible default exists.",
            "Use constrained fields for business rules like string length or number ranges.",
            "Do not treat validation as authorization. They solve different problems.",
        ],
        "common_traps": [
            "Confusing `Optional[str]` with a field that can be omitted.",
            "Letting models grow into business-logic classes.",
            "Trusting external data before validation.",
            "Ignoring validation error details.",
        ],
        "interview": [
            "Explain validation vs serialization.",
            "Know optional fields and defaults.",
            "Mention model boundaries for untrusted input.",
            "Explain why FastAPI and Pydantic are often used together.",
        ],
        "docs": [
            {"label": "Pydantic: Models", "url": "https://docs.pydantic.dev/latest/concepts/models/"},
            {"label": "Pydantic: Fields", "url": "https://docs.pydantic.dev/latest/concepts/fields/"},
        ],
    },
    {
        "id": "async",
        "track": "Backend",
        "title": "Async Python",
        "level": "Intermediate",
        "intro": "Async Python is about waiting efficiently. It is useful for network calls, database calls, file operations, and API servers that handle many I/O-bound tasks. It does not automatically make CPU-heavy Python code faster. Interviewers often test whether you know when async helps and when it does not.",
        "mental_model": "An event loop runs tasks. When one task awaits slow I/O, the loop can let another task make progress. This is concurrency, not automatic parallel CPU execution.",
        "syntax": "import asyncio\n\nasync def fetch_user(user_id):\n    await asyncio.sleep(1)\n    return {'id': user_id}\n\nasync def main():\n    user = await fetch_user(10)\n    print(user)\n\nasyncio.run(main())",
        "example": "Use async all the way through the stack when possible: async route, async HTTP client, async database driver. Mixing async code with blocking sync calls can remove the benefit.",
        "must_know": [
            "`async def` creates a coroutine function.",
            "`await` pauses the current coroutine until the awaited operation completes.",
            "The event loop coordinates async tasks.",
            "Async is best for I/O-bound workloads, not heavy CPU calculations.",
            "Blocking calls inside async code can freeze other tasks.",
        ],
        "common_traps": [
            "Calling an async function without awaiting it.",
            "Using `time.sleep()` inside async code instead of `asyncio.sleep()`.",
            "Assuming async means multiple CPU cores are used.",
            "Mixing sync database clients into async route handlers.",
        ],
        "interview": [
            "Explain concurrency vs parallelism.",
            "Know when async helps.",
            "Avoid blocking calls inside async routes.",
            "Describe how async relates to FastAPI.",
        ],
        "docs": [
            {"label": "Python Docs: asyncio", "url": "https://docs.python.org/3/library/asyncio.html"},
            {"label": "Python Docs: Coroutines and Tasks", "url": "https://docs.python.org/3/library/asyncio-task.html"},
        ],
    },
    {
        "id": "langchain",
        "track": "AI Apps",
        "title": "LangChain",
        "level": "Intermediate",
        "intro": "LangChain helps build LLM applications by giving common abstractions for models, prompts, tools, retrievers, structured output, and agents. In interviews, avoid saying only 'it connects to LLMs'. Explain which pieces you used and why. The real skill is controlling inputs, outputs, tool access, retrieval quality, and observability.",
        "mental_model": "An LLM app is a pipeline: prepare context, format a prompt, call a model, parse the response, maybe call tools, and evaluate the result. LangChain gives reusable building blocks for those steps.",
        "syntax": "prompt -> model -> output parser\nretriever -> context -> prompt -> model -> answer\nagent -> decide -> tool call -> observe -> respond",
        "example": "A RAG chain retrieves relevant documents, inserts them into a prompt as context, calls a chat model, and returns an answer with source citations.",
        "must_know": [
            "Prompts shape the task, constraints, examples, and expected output.",
            "Models are provider-specific, but LangChain can standardize the calling interface.",
            "Tools let the model request external actions or data.",
            "Retrievers fetch context for RAG.",
            "Output parsers or structured output help turn model text into usable data.",
            "Tracing and evaluation matter because LLM behavior can drift.",
        ],
        "common_traps": [
            "Using one giant prompt instead of clear components.",
            "Letting tools run dangerous actions without approval.",
            "Ignoring retrieval quality and blaming the model.",
            "Not logging prompts, retrieved context, and outputs during debugging.",
        ],
        "interview": [
            "Explain prompts, models, tools, retrievers, and structured output.",
            "Know RAG failure modes: bad retrieval, stale data, hallucination.",
            "Mention observability and evaluation.",
            "Explain when you would not use an agent.",
        ],
        "docs": [
            {"label": "LangChain Python Docs", "url": "https://docs.langchain.com/oss/python"},
            {"label": "LangChain Providers and Models", "url": "https://docs.langchain.com/oss/python/concepts/providers-and-models"},
        ],
    },
    {
        "id": "langgraph",
        "track": "AI Apps",
        "title": "LangGraph",
        "level": "Intermediate",
        "intro": "LangGraph is for building controlled, stateful agent workflows. Instead of one long prompt doing everything, you define state, nodes, edges, and conditions. This is useful when a workflow needs retries, branching, tool calls, memory, checkpoints, human approval, or long-running execution.",
        "mental_model": "A graph is a workflow. State carries information. Nodes do work. Edges decide where execution goes next. Checkpoints let the workflow pause, resume, and inspect state.",
        "syntax": "state -> classify_node -> retrieve_node -> draft_node -> approval_node -> action_node\n\nconditional edge: if risky, ask human; otherwise continue",
        "example": "An incident assistant graph could classify an alert, collect logs, summarize likely causes, ask for human approval, run a safe diagnostic command, then write a final report.",
        "must_know": [
            "State is the shared data structure passed through the graph.",
            "Nodes are functions that read and update state.",
            "Edges connect nodes; conditional edges choose the next node.",
            "Checkpoints support persistence, review, and resume.",
            "Human-in-the-loop is important before risky actions.",
        ],
        "common_traps": [
            "Using LangGraph when a simple chain is enough.",
            "Putting all logic into one node.",
            "Letting state become an unstructured dumping ground.",
            "Skipping approval steps for actions with real-world impact.",
        ],
        "interview": [
            "Explain state, nodes, edges, and checkpoints.",
            "Know why graphs are easier to control than one giant prompt.",
            "Mention human-in-the-loop for risky actions.",
            "Compare LangChain agents with LangGraph workflows.",
        ],
        "docs": [
            {"label": "LangGraph Overview", "url": "https://docs.langchain.com/oss/python/langgraph/overview"},
            {"label": "LangChain Product Concepts", "url": "https://docs.langchain.com/oss/python/concepts/products"},
        ],
    },
    {
        "id": "mcp",
        "track": "AI Apps",
        "title": "MCP",
        "level": "Intermediate",
        "intro": "Model Context Protocol standardizes how AI clients connect to tools and data. Instead of every AI app inventing its own plugin system, MCP defines a client-server pattern for exposing tools, resources, prompts, and transports. In interviews, emphasize permissions and boundaries because tool access can be powerful.",
        "mental_model": "An AI client talks to an MCP server. The server exposes capabilities such as tools or resources. The client decides what to request, and the server executes only what it is allowed to expose.",
        "syntax": "AI client <-> MCP server <-> tools/resources\n\nTool: run_search(query)\nResource: file://notes/interview.md\nPrompt: summarize_incident",
        "example": "An MCP server can expose a read-only documentation search resource, a database lookup tool, or a ticket-creation tool. A well-designed server limits what the model can access and records what was called.",
        "must_know": [
            "Tools are callable actions.",
            "Resources are data objects the client can read.",
            "Prompts are reusable templates exposed by the server.",
            "Transports define how client and server communicate.",
            "Least privilege matters: expose only the minimum safe capability.",
        ],
        "common_traps": [
            "Treating MCP as the AI model itself.",
            "Exposing write actions without authentication or approval.",
            "Giving broad filesystem or database access without clear limits.",
            "Not logging tool calls.",
        ],
        "interview": [
            "Explain tools vs resources.",
            "Mention permissions and least privilege.",
            "Know why standardized tool interfaces matter.",
            "Describe one safe MCP server you could build.",
        ],
        "docs": [
            {"label": "Model Context Protocol: Learn", "url": "https://modelcontextprotocol.io/docs/learn"},
            {"label": "MCP Specification Overview", "url": "https://modelcontextprotocol.io/specification/2024-11-05/basic/index"},
        ],
    },
    {
        "id": "rag-vectors",
        "track": "AI Apps",
        "title": "RAG, Embeddings, and Vector DBs",
        "level": "Intermediate",
        "intro": "RAG gives an LLM external knowledge at answer time. Embeddings convert text into vectors, vector search finds semantically similar chunks, and the retrieved chunks are placed into the prompt. RAG can reduce hallucination, but it does not guarantee correctness. The quality depends on chunking, retrieval, ranking, prompt design, and evaluation.",
        "mental_model": "Documents become chunks. Chunks become embeddings. Embeddings go into a vector store. A user question becomes another embedding. Similar chunks are retrieved and passed to the model as context.",
        "syntax": "documents -> chunks -> embeddings -> vector store\nquestion -> embedding -> top-k retrieval -> prompt context -> answer with citations",
        "example": "For an interview assistant, store Python notes as chunks, retrieve the top matching chunks for a user's question, ask the model to answer only from retrieved context, and show source links.",
        "must_know": [
            "Embeddings represent semantic meaning numerically.",
            "Chunk size affects both retrieval quality and context cost.",
            "Top-k retrieval returns the nearest matching chunks, but nearest is not always best.",
            "Metadata filters help limit retrieval to a product, date, file, or topic.",
            "Reranking can improve result order after initial vector search.",
            "Evaluation should use known questions, expected sources, and answer checks.",
        ],
        "common_traps": [
            "Assuming RAG fully eliminates hallucination.",
            "Chunking documents randomly without preserving meaning.",
            "Not storing source metadata.",
            "Testing only with easy questions.",
        ],
        "interview": [
            "Know hallucination is reduced, not eliminated.",
            "Explain why chunk size matters.",
            "Mention evaluation with known questions and expected sources.",
            "Describe how you would debug a bad RAG answer.",
        ],
        "docs": [
            {"label": "OpenAI Embeddings Guide", "url": "https://platform.openai.com/docs/guides/embeddings"},
            {"label": "LangChain Retrieval Concepts", "url": "https://docs.langchain.com/oss/python/concepts/retrieval"},
        ],
    },
    {
        "id": "python-devops",
        "track": "DevOps",
        "title": "Python for DevOps",
        "level": "Intermediate",
        "intro": "Python for DevOps is about automating repeatable operational work safely. You use Python to inspect files, parse logs, call HTTP APIs, manage configuration, run controlled shell commands, check service health, process JSON/YAML, and glue tools together. The interview goal is not to replace Terraform, Ansible, Bash, or CI/CD systems with Python; it is to know when a small Python tool makes operational work more reliable and testable.",
        "mental_model": "A DevOps Python script is usually a controlled automation pipeline: read inputs, validate them, inspect current state, perform a small action or dry run, record output, and fail clearly when something is unsafe.",
        "syntax": "from pathlib import Path\nimport json\nimport subprocess\n\nconfig_path = Path('service.json')\nconfig = json.loads(config_path.read_text())\n\nresult = subprocess.run(\n    ['python', '--version'],\n    capture_output=True,\n    text=True,\n    check=False,\n)\nprint(result.stdout or result.stderr)",
        "example": "def parse_health(lines):\n    summary = {'ok': 0, 'fail': 0}\n    for line in lines:\n        service, status = line.split(':', 1)\n        status = status.strip().lower()\n        if status in summary:\n            summary[status] += 1\n    return summary\n\nprint(parse_health(['api: ok', 'worker: fail', 'db: ok']))",
        "must_know": [
            "Use `pathlib` for filesystem paths instead of fragile string path handling.",
            "Use `subprocess.run()` with argument lists, timeouts, captured output, and explicit error handling.",
            "Use `json`, YAML parsers, and environment variables to handle configuration cleanly.",
            "Make scripts idempotent where possible: running twice should not cause surprising damage.",
            "Support dry-run behavior before actions that change infrastructure or production data.",
            "Log what the script checked, changed, skipped, and failed.",
        ],
        "common_traps": [
            "Building shell commands by string concatenation with untrusted input.",
            "Writing scripts that only work from one current directory.",
            "Ignoring return codes from external commands.",
            "Hardcoding secrets or hostnames into scripts.",
            "Automating destructive actions without confirmation, backups, or dry runs.",
        ],
        "interview": [
            "Explain when Python is better than Bash for automation.",
            "Know how to safely call external commands.",
            "Mention idempotency, dry runs, logging, and error handling.",
            "Describe how Python fits with CI/CD, Docker, Ansible, and cloud APIs.",
        ],
        "docs": [
            {"label": "Python Docs: subprocess", "url": "https://docs.python.org/3/library/subprocess.html"},
            {"label": "Python Docs: pathlib", "url": "https://docs.python.org/3/library/pathlib.html"},
            {"label": "Docker Docs: Engine SDKs", "url": "https://docs.docker.com/reference/api/engine/sdk/"},
            {"label": "Ansible Docs: Playbooks", "url": "https://docs.ansible.com/projects/ansible-core/devel/playbook_guide/playbooks_intro.html"},
        ],
    },
    {
        "id": "sql-http-git",
        "track": "Must-Know Extras",
        "title": "SQL, HTTP, Git, and Linux Basics",
        "level": "Beginner",
        "intro": "Python interviews often include practical engineering basics. You may be asked how an API request works, how to query a table, how to use Git safely, or how to inspect files and processes on a server. You do not need to be a database admin or DevOps expert, but you should be comfortable with the daily vocabulary.",
        "mental_model": "Backend work connects layers: code receives HTTP, reads configuration, talks to databases, logs errors, runs on a machine, and ships through Git. Knowing the basics lets you debug across those layers.",
        "syntax": "SELECT id, name FROM users WHERE active = true;\n\nGET /users/123 -> read user\nPOST /users -> create user\n\n git status\n git add app.py\n git commit -m \"add lesson\"\n\n echo $PATH\n ls -la\n grep \"error\" app.log",
        "example": "If a FastAPI endpoint returns 500, check the request, route logs, traceback, environment variables, database connection, and recent Git changes.",
        "must_know": [
            "SQL basics: SELECT, WHERE, ORDER BY, LIMIT, INSERT, UPDATE, DELETE, and simple JOINs.",
            "HTTP basics: methods, headers, request body, response body, and status codes.",
            "Git basics: status, diff, add, commit, branch, merge, pull, push, and pull requests.",
            "Linux basics: paths, permissions, environment variables, processes, logs, and pipes.",
            "Debugging usually means following the request through each layer.",
        ],
        "common_traps": [
            "Not understanding the difference between 401 and 403.",
            "Committing secrets like API keys.",
            "Running commands without checking the current directory.",
            "Changing production data without a WHERE clause.",
        ],
        "interview": [
            "Know common HTTP codes: 200, 201, 400, 401, 403, 404, 422, 500.",
            "Know joins at a basic level.",
            "Know git branch, commit, merge, pull request.",
            "Explain how you would debug a failing API request.",
        ],
        "docs": [
            {"label": "MDN HTTP Reference", "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference"},
            {"label": "Git Book", "url": "https://git-scm.com/book/en/v2"},
            {"label": "PostgreSQL Tutorial", "url": "https://www.postgresql.org/docs/current/tutorial.html"},
        ],
    },
]

REAL_WORLD_IMPLEMENTATIONS = {
    "python-basics": [
        "A support automation script may read a list of server names, loop through them, and print a health summary. That simple workflow uses variables, strings, lists, conditions, loops, and readable error messages.",
        "A data cleanup script may convert text input into numbers, skip invalid rows, and build a clean output file. The basics decide whether that script is safe and understandable.",
    ],
    "data-structures": [
        "A log analyzer can use a dictionary to count error codes, a set to track unique users, and a list to keep the latest events in order.",
        "A small API service may return dictionaries as JSON, keep database rows as lists of records, and use sets to remove duplicate permissions.",
    ],
    "functions": [
        "Production scripts become easier to maintain when each operation is a function: `load_config`, `validate_payload`, `summarize_errors`, and `write_report`.",
        "A function boundary lets you test business logic without starting a server, calling a real API, or touching the filesystem.",
    ],
    "oop": [
        "A monitoring tool might model `Service`, `HealthCheck`, and `Alert` objects when each item has both data and behavior.",
        "A retry policy, API client, or configuration object is often clearer as a small class than as a loose group of dictionaries and helper functions.",
    ],
    "errors-testing": [
        "A real script should fail with a clear message when a config file is missing, an API returns invalid JSON, or a command exits with a non-zero status.",
        "Tests protect automation from silent regressions. Before changing parsing logic, write tests for valid input, empty input, malformed input, and edge cases.",
    ],
    "fastapi": [
        "A real FastAPI service might expose `/health`, `/tickets`, and `/incidents` endpoints, validate request bodies, call service-layer functions, and return predictable status codes.",
        "In a team setting, FastAPI's OpenAPI docs help frontend developers, QA, and other backend services understand how to call your API.",
    ],
    "pydantic": [
        "Use Pydantic at trust boundaries: incoming HTTP payloads, environment configuration, LLM structured outputs, queue messages, and third-party API responses.",
        "A good model turns unclear data into an explicit contract, so errors are caught near the boundary instead of deep inside business logic.",
    ],
    "async": [
        "An async API gateway can wait on several downstream services without blocking the whole server process for each network call.",
        "A background job that checks many URLs can use async I/O to keep many requests in flight while still using one readable Python program.",
    ],
    "langchain": [
        "A document assistant can use LangChain to combine a retriever, prompt template, chat model, and structured output parser into a repeatable answer pipeline.",
        "A tool-using assistant can call search, ticket lookup, or database tools, but production use should log prompts, tool calls, retrieved context, and final answers.",
    ],
    "langgraph": [
        "An incident workflow can classify an alert, retrieve logs, draft a diagnosis, request approval, run a safe diagnostic command, and summarize the result as separate graph nodes.",
        "Graphs are useful when a workflow needs control, pause/resume, retries, checkpoints, or human review before risky actions.",
    ],
    "mcp": [
        "An internal developer assistant can use MCP servers to expose read-only documentation search, issue lookup, repository search, or safe ticket creation.",
        "A well-designed MCP server limits capability scope, authenticates access, and logs tool calls because the model may request actions on behalf of a user.",
    ],
    "rag-vectors": [
        "A company knowledge assistant can chunk handbook pages, embed each chunk, store vectors with source metadata, retrieve relevant chunks, and answer with citations.",
        "Real RAG systems need evaluation: known questions, expected source documents, answer quality checks, and monitoring for retrieval failures.",
    ],
    "python-devops": [
        "A DevOps script can validate a deployment config, check service health, call cloud or container APIs, produce a dry-run plan, and log every action.",
        "Python is useful when Bash becomes hard to test: complex JSON/YAML parsing, API calls, retries, reporting, and cross-platform path handling.",
    ],
    "sql-http-git": [
        "A backend debugging session often crosses all these basics: inspect an HTTP request, read server logs, query a database row, check environment variables, and review the Git diff that changed behavior.",
        "These skills help you work with other engineers because they are the shared language of everyday software delivery.",
    ],
}


DIRECTIONAL_OVERVIEWS = {
    "python-basics": {
        "intro": "Python Basics is where you learn how Python actually behaves while code is running. You will start small: evaluate expressions, store values in variables, work with strings and lists, make decisions with if/elif/else, repeat work with loops, and package logic inside functions. This topic is not about memorizing syntax lines. It is about building a mental picture of execution so you can read code, debug confidently, and write clean small programs that do what you expect.",
        "mental_model": "Think of a Python file as a sequence of steps. Python runs from top to bottom, one statement at a time. Expressions create values. Assignment gives those values names. Indentation marks which lines belong to the same block. Conditions choose one path. Loops repeat a block across items. Functions let you bundle steps into reusable units and return results.",
        "outcome": "By the end of this topic, you should be able to read a short Python script and explain what each line does, what each variable currently holds, and why a branch or loop behaves the way it does. You should also be able to write and test small functions, and fix common beginner issues like NameError, IndexError, and indentation mistakes.",
        "syntax": "price = 100.50\ntax_rate = 12.5 / 100\ntotal = round(price + price * tax_rate, 2)\n\nname = 'Ada Lovelace'\ninitials = name[0] + name[4]\n\nscores = [72, 88, 91]\nscores.append(95)\n\nif total > 100:\n    label = 'review'\nelif total == 100:\n    label = 'exact'\nelse:\n    label = 'ok'\n\nfor score in scores:\n    print(score)\n\nfor index in range(len(scores)):\n    scores[index] = scores[index] + 1\n\ndef passed(score, cutoff=60):\n    return score >= cutoff",
        "example": "def summarize_cart(prices, tax_rate):\n    subtotal = sum(prices)\n    tax = subtotal * tax_rate\n    total = round(subtotal + tax, 2)\n\n    if total >= 100:\n        status = 'manager review'\n    else:\n        status = 'approved'\n\n    return {\n        'item_count': len(prices),\n        'subtotal': subtotal,\n        'total': total,\n        'status': status,\n    }\n\nprint(summarize_cart([19.99, 35.50, 12.00], 0.08))",
        "must_know": [
            "The interpreter can evaluate expressions immediately; this is useful for learning, debugging, and checking assumptions.",
            "`/` returns a float, `//` performs floor division, `%` returns a remainder, and `**` performs exponentiation.",
            "`=` binds a name to a value. Reading a name before assignment raises `NameError`.",
            "Strings are immutable sequences. You can index and slice them, but you create a new string when you need a changed value.",
            "Lists are mutable sequences. Indexing returns an item, slicing returns a new list, and methods like `append()` change the list.",
            "`if`, `elif`, and `else` select a path. `for` loops iterate over the items of a sequence or other iterable.",
            "`range()` creates an iterable progression of numbers. Its stop value is excluded.",
            "`def` creates a function object. Function bodies are indented, parameters become local names, and `return` sends a value back to the caller.",
        ],
        "common_traps": [
            "Assuming `17 / 3` returns an integer. In Python, `/` returns a float; use `//` for floor division.",
            "Trying to modify a character inside a string. Strings are immutable, so build a new string instead.",
            "Using an index that is outside the sequence length, which raises `IndexError`.",
            "Changing a collection while iterating over the same collection without understanding the side effects.",
            "Forgetting that `range(5)` produces 0, 1, 2, 3, 4 and does not include 5.",
            "Printing inside a function when the caller or test expects a returned value.",
        ],
        "interview": [
            "Explain assignment as name binding, not as a permanently typed box.",
            "Trace arithmetic and string/list slicing without running the code.",
            "Know when a sequence operation creates a new value versus mutating the existing object.",
            "Be able to explain why `range(stop)` excludes the stop value.",
            "Use `return` for reusable code and tests; use `print()` for display/debug output.",
        ],
        "docs": [
            {"label": "Python Tutorial", "url": "https://docs.python.org/3/tutorial/index.html"},
            {"label": "Informal Introduction: Numbers, Text, Lists", "url": "https://docs.python.org/3/tutorial/introduction.html"},
            {"label": "Control Flow Tools", "url": "https://docs.python.org/3/tutorial/controlflow.html"},
        ],
        "lesson_sections": [
            {
                "title": "1. Start in the Interpreter",
                "body": "The official tutorial begins with interactive examples for a reason: Python is easiest to learn when you run one small line at a time. Type an expression, observe the output, then add the next line. This habit helps you debug faster because you test your assumptions early instead of guessing. Comments begin with # and are ignored by Python unless the # appears inside a string literal.",
                "source_label": "Python Tutorial: Informal Introduction",
                "source_url": "https://docs.python.org/3/tutorial/introduction.html",
            },
            {
                "title": "2. Numbers, Operators, and Variables",
                "body": "Python arithmetic uses familiar operators: +, -, *, and /. Parentheses control order. The details matter: / returns a float, // does floor division, % gives the remainder, and ** does powers. Assignment with = binds a name to a value. If you try to use a name before assigning it, Python raises NameError. These are small rules, but they explain many early bugs.",
                "source_label": "Python Tutorial: Numbers",
                "source_url": "https://docs.python.org/3/tutorial/introduction.html#numbers",
            },
            {
                "title": "3. Strings: Read, Slice, Rebuild",
                "body": "Strings are Python's text type. You can create them with single or double quotes and use escape sequences like \\n. Strings are sequences, so indexing gives one character and slicing gives a section. A key concept: strings are immutable. You cannot change one character in place, so updates are done by creating a new string from pieces.",
                "source_label": "Python Tutorial: Text",
                "source_url": "https://docs.python.org/3/tutorial/introduction.html#text",
            },
            {
                "title": "4. Lists: Store and Update Collections",
                "body": "Lists hold multiple values in order. Like strings, they support indexing and slicing, but unlike strings they are mutable. That means you can append, replace, and reorder items. Learning this mutability difference early makes later topics much easier, especially debugging and function behavior.",
                "source_label": "Python Tutorial: Lists",
                "source_url": "https://docs.python.org/3/tutorial/introduction.html#lists",
            },
            {
                "title": "5. Control Flow: Branches and Loops",
                "body": "Control flow decides what runs next. if, elif, and else choose between paths. for loops iterate through each item in a sequence. range() is used when you need numeric repetition; the stop value is excluded, so range(5) gives 0 through 4. break exits a loop, continue skips to the next cycle, and pass is a placeholder when you need syntactically valid code but no action yet.",
                "source_label": "Python Tutorial: Control Flow",
                "source_url": "https://docs.python.org/3/tutorial/controlflow.html",
            },
            {
                "title": "6. Functions: Write Once, Reuse Many Times",
                "body": "Functions start with def, followed by a name, parameters, and an indented body. When you call a function, arguments fill those parameters. return sends data back to the caller; if there is no return value, Python returns None. For labs and real code, return is what makes logic testable and reusable. print is for display, not for passing values to other code.",
                "source_label": "Python Tutorial: Defining Functions",
                "source_url": "https://docs.python.org/3/tutorial/controlflow.html#defining-functions",
            },
        ],
    },
    "data-structures": {
        "intro": "Data structures are the containers you use to organize information. Lists keep ordered items, dictionaries connect keys to values, sets track uniqueness, and tuples represent fixed groups. Choosing the right container often makes code shorter, faster, and easier to explain.",
        "outcome": "You should be able to choose between list, dict, set, and tuple for a small problem, then explain why that choice fits the data and operation.",
        "lesson_sections": [
            {"title": "Lists", "body": "Use a list when order matters or when you need to process items one by one. Lists are good for append, sort, slice, and iteration. They are less ideal for repeated membership checks on large data."},
            {"title": "Dictionaries", "body": "Use a dictionary when you need to look up a value by a key. Common examples are counting words, mapping user IDs to profiles, storing config values, and grouping records by category."},
            {"title": "Sets", "body": "Use a set when you care about uniqueness or fast membership checks. Sets are useful for duplicate detection, permission checks, and comparing groups of items."},
            {"title": "Tuples", "body": "Use a tuple for a fixed group of related values, such as coordinates, a database row shape, or a small return value like `(success, message)`."},
        ],
    },
    "functions": {
        "intro": "Functions let you turn a piece of logic into a reusable, testable unit. They are one of the most important tools for writing clean Python because they make inputs, outputs, and responsibility visible.",
        "outcome": "You should be able to write a small function with clear parameters, return a value, test it with examples, and explain what responsibility the function owns.",
        "lesson_sections": [
            {"title": "Function Contract", "body": "A function contract means: what inputs does this function accept, what output does it return, and what behavior does it promise? Clear contracts make code easier to test and reuse."},
            {"title": "Parameters and Arguments", "body": "Parameters are names in the function definition. Arguments are the actual values passed when calling it. Python supports positional arguments, keyword arguments, and defaults."},
            {"title": "Return vs Print", "body": "`return` gives a value back to the caller. `print` only displays text. In learning apps, APIs, and tests, returning values is usually more useful because the result can be checked and reused."},
            {"title": "Small Functions", "body": "A function should usually do one clear job. If you cannot name the function without using 'and', it may be trying to do too much."},
        ],
    },
    "oop": {
        "intro": "Object-oriented programming is a way to group data and behavior. It is useful when a concept in your program has state and actions, such as a user, ticket, retry policy, API client, or health check.",
        "outcome": "You should be able to create a class, initialize instance attributes, write methods, and decide when a class is clearer than a plain function.",
        "lesson_sections": [
            {"title": "Classes and Instances", "body": "A class is a blueprint. An instance is one object created from that blueprint. Each instance can have its own attributes, such as `user.name` or `policy.max_attempts`."},
            {"title": "Methods and self", "body": "A method is a function attached to a class. The first parameter, usually named `self`, refers to the current instance so the method can read or update that object's data."},
            {"title": "Composition Before Inheritance", "body": "Inheritance can reuse behavior, but beginners often overuse it. Composition means building an object from smaller objects, and it is often simpler and easier to change."},
            {"title": "When Not to Use OOP", "body": "If a problem is just a simple transformation from input to output, a function may be better. Use classes when the code becomes clearer by keeping related state and behavior together."},
        ],
    },
    "errors-testing": {
        "intro": "Errors and tests help you build reliable programs. Instead of fearing failures, you learn to read them, isolate them, and prevent the same problem from returning.",
        "outcome": "You should be able to read a traceback, catch specific exceptions, write basic assertions, and create tests for normal and edge cases.",
        "lesson_sections": [
            {"title": "Reading Tracebacks", "body": "A traceback shows the path Python followed before it failed. Start with the exception type and message, then look for the line in your own code that triggered it."},
            {"title": "Specific Exceptions", "body": "Catch the error you expect, such as `ValueError` when converting text to an integer. Avoid bare `except` because it can hide programming mistakes and make debugging harder."},
            {"title": "Testing Mindset", "body": "A test is a small statement of expected behavior. Good tests include a normal case, an empty case, invalid input, duplicates, zero, and boundary values."},
            {"title": "Debugging Process", "body": "Change one thing at a time. Reproduce the issue, form a hypothesis, test it, and keep the smallest failing example you can create."},
        ],
    },
    "fastapi": {
        "intro": "FastAPI helps you build HTTP APIs with Python. You define routes, validate incoming data, return structured responses, and get automatic API documentation from your code.",
        "outcome": "You should be able to explain how a request reaches a route, how data is validated, and how a response is returned with the right status code.",
        "lesson_sections": [
            {"title": "Request Lifecycle", "body": "A client sends an HTTP request with a method, path, headers, and sometimes a body. FastAPI matches the route, validates inputs, calls your function, and serializes the result."},
            {"title": "Path, Query, and Body Data", "body": "Path parameters identify a resource, query parameters filter or modify a request, and body data carries structured payloads for create or update operations."},
            {"title": "Validation with Models", "body": "FastAPI commonly uses Pydantic models to validate request bodies. This keeps invalid data from reaching deeper business logic."},
            {"title": "Status Codes and Errors", "body": "Status codes communicate what happened. A good API does not return 200 for every outcome; it uses meaningful success and error codes."},
        ],
    },
    "pydantic": {
        "intro": "Pydantic is a validation and serialization library. It helps turn uncertain external data into predictable Python objects with explicit fields and rules.",
        "outcome": "You should be able to define a model, validate incoming data, understand validation errors, and serialize model data for APIs or storage.",
        "lesson_sections": [
            {"title": "Models as Contracts", "body": "A Pydantic model describes what shape data should have. This creates a clear contract between external input and internal code."},
            {"title": "Validation", "body": "Validation checks types and rules. For example, a priority might need to be an integer between 1 and 5. Invalid input produces structured error details."},
            {"title": "Defaults and Optional Fields", "body": "Defaults provide values when input is missing. Optional fields allow `None`. These are related ideas, but they are not the same thing."},
            {"title": "Serialization", "body": "Serialization converts a model back into a dictionary or JSON-friendly form. This is useful for API responses, logs, messages, and storage."},
        ],
    },
    "async": {
        "intro": "Async Python lets one program handle many waiting tasks efficiently. It is most useful when the program waits on I/O such as HTTP calls, database queries, files, or message queues.",
        "outcome": "You should be able to explain `async def`, `await`, the event loop, and why async helps I/O-bound programs but not every CPU-heavy task.",
        "lesson_sections": [
            {"title": "Concurrency, Not Magic Speed", "body": "Async allows tasks to take turns while waiting. It does not automatically make CPU-heavy calculations faster or use all CPU cores."},
            {"title": "Coroutines", "body": "Calling an `async def` function creates a coroutine. The coroutine must be awaited or scheduled before its body actually runs."},
            {"title": "The Event Loop", "body": "The event loop coordinates async tasks. When one task awaits I/O, the loop can run another task until the first one is ready again."},
            {"title": "Blocking Calls", "body": "Using blocking functions inside async code can freeze the event loop. Use async-compatible libraries when building async services."},
        ],
    },
    "langchain": {
        "intro": "LangChain gives building blocks for LLM applications: prompts, models, tools, retrievers, structured outputs, and observability. It helps organize AI workflows that would otherwise become scattered glue code.",
        "outcome": "You should be able to describe how a prompt, model, retriever, tool, and output parser fit together in a practical LLM application.",
        "lesson_sections": [
            {"title": "Prompt to Model to Output", "body": "A simple LLM flow formats a prompt, sends it to a model, and parses the result. The quality depends on clear instructions, useful context, and output constraints."},
            {"title": "Retrieval", "body": "Retrievers bring external knowledge into the prompt. This is central to RAG systems where the model should answer using documents or records."},
            {"title": "Tools", "body": "Tools allow an AI system to request actions or data, such as search, database lookup, or ticket creation. Tool use needs permissions and logging."},
            {"title": "Evaluation and Tracing", "body": "LLM applications must be inspected. Trace prompts, inputs, retrieved context, tool calls, and outputs so you can debug quality issues."},
        ],
    },
    "langgraph": {
        "intro": "LangGraph helps build stateful AI workflows. It is useful when a task has multiple steps, branches, retries, memory, approvals, or long-running execution.",
        "outcome": "You should be able to explain state, nodes, edges, conditional routing, and when a graph is better than a simple chain.",
        "lesson_sections": [
            {"title": "State", "body": "State is the shared information passed through the graph. It may contain the user request, retrieved context, tool results, decisions, and final answer."},
            {"title": "Nodes", "body": "A node is a unit of work. One node might classify input, another might retrieve documents, and another might draft a response."},
            {"title": "Edges and Branching", "body": "Edges decide where execution goes next. Conditional edges let the workflow branch based on risk, confidence, missing data, or user approval."},
            {"title": "Checkpoints and Human Review", "body": "Checkpoints allow workflows to pause, resume, and inspect state. Human review is important before risky actions."},
        ],
    },
    "mcp": {
        "intro": "Model Context Protocol defines a standard way for AI clients to connect with tools, resources, and prompts. It is a bridge between an AI application and external capabilities.",
        "outcome": "You should be able to explain MCP clients, servers, tools, resources, prompts, and why permissions matter.",
        "lesson_sections": [
            {"title": "Client and Server", "body": "An MCP client is the AI application that wants context or capabilities. An MCP server exposes controlled tools, resources, or prompts."},
            {"title": "Tools", "body": "Tools are callable actions. They might search files, query a database, create a ticket, or run a safe command."},
            {"title": "Resources", "body": "Resources are data the client can read, such as files, documents, schemas, or records. They should be scoped carefully."},
            {"title": "Permissions", "body": "MCP servers must be designed with least privilege. Expose only what is needed, log calls, and require approval for risky actions."},
        ],
    },
    "rag-vectors": {
        "intro": "RAG combines retrieval with generation. The system searches external knowledge, places relevant context into the prompt, and asks the model to answer using that context.",
        "outcome": "You should be able to explain chunking, embeddings, vector search, retrieval quality, citations, and evaluation.",
        "lesson_sections": [
            {"title": "Chunking", "body": "Large documents are split into smaller chunks so they can be embedded and retrieved. Good chunking preserves meaning and source metadata."},
            {"title": "Embeddings", "body": "Embeddings convert text into vectors. Similar meanings should be close in vector space, which makes semantic search possible."},
            {"title": "Retrieval", "body": "A user question is embedded and compared against stored vectors. The top results become context for the LLM."},
            {"title": "Evaluation", "body": "RAG must be tested with known questions, expected sources, answer quality checks, and failure analysis. Retrieval errors often look like model errors."},
        ],
    },
    "python-devops": {
        "intro": "Python for DevOps is about safe, repeatable automation. You use Python to read configs, inspect systems, call APIs, parse logs, run controlled commands, and report what happened.",
        "outcome": "You should be able to write a small automation script that validates input, supports dry-run behavior, handles errors, and logs useful output.",
        "lesson_sections": [
            {"title": "Automation Boundaries", "body": "Good automation has clear inputs, clear outputs, and safe limits. It should not silently change systems without showing what it plans to do."},
            {"title": "Files and Config", "body": "DevOps scripts often read JSON, YAML, environment variables, and filesystem paths. Use structured parsers and `pathlib` instead of fragile string handling."},
            {"title": "Running Commands", "body": "Use `subprocess.run()` with argument lists, captured output, timeouts, and return-code checks. Avoid building shell strings from untrusted input."},
            {"title": "Operational Safety", "body": "Prefer dry runs, idempotent actions, clear logs, and explicit failure handling. These habits matter more than clever code."},
        ],
    },
    "sql-http-git": {
        "intro": "SQL, HTTP, Git, and terminal basics are the shared working language of software teams. They help you debug applications, collaborate with others, and understand how code runs outside your editor.",
        "outcome": "You should be able to follow a web request, inspect a database record, understand a Git change, and use terminal commands carefully.",
        "lesson_sections": [
            {"title": "HTTP", "body": "HTTP describes how clients and servers communicate. Methods show intent, status codes show outcome, and headers/body carry metadata and data."},
            {"title": "SQL", "body": "SQL lets you read and change relational data. Start with SELECT, WHERE, ORDER BY, LIMIT, INSERT, UPDATE, DELETE, and simple JOINs."},
            {"title": "Git", "body": "Git tracks code changes. You should understand status, diff, add, commit, branch, merge, pull, push, and pull requests."},
            {"title": "Terminal Basics", "body": "The terminal helps you inspect files, run scripts, check environment variables, search logs, and understand what directory or machine you are working in."},
        ],
    },
}


def _enrich_topics() -> None:
    """Merge real-world implementations and directional overviews into TOPICS.

    Called once at module load time. Separated into a function so it is
    explicit, testable, and does not surprise readers of the module.
    """
    for topic in TOPICS:
        topic["real_world"] = REAL_WORLD_IMPLEMENTATIONS.get(topic["id"], [])
        overview = DIRECTIONAL_OVERVIEWS.get(topic["id"])
        if overview:
            topic.update(overview)


_enrich_topics()
