EXERCISES = [
    {
        "id": "calculate-receipt-total",
        "topic_id": "python-basics",
        "title": "Calculate Receipt Total",
        "difficulty": "Beginner",
        "difficulty_order": 1,
        "prompt": "Write `calculate_total(prices, tax_rate)` that returns the rounded total for a list of prices after tax. This practices numbers, assignment, `sum()`, multiplication, and returning values.",
        "starter": "def calculate_total(prices, tax_rate):\n    # subtotal is the sum of all prices\n    # tax is subtotal * tax_rate\n    # return the total rounded to 2 decimals\n    pass\n",
        "tests": [
            {"label": "two items", "call": "calculate_total([10, 20], 0.1)", "expected": 33.0},
            {"label": "round cents", "call": "calculate_total([19.99, 5.50], 0.08)", "expected": 27.53},
            {"label": "no tax", "call": "calculate_total([3, 7], 0)", "expected": 10},
            {"label": "empty cart", "call": "calculate_total([], 0.2)", "expected": 0},
        ],
        "hint": "Build the calculation in named steps: subtotal, tax, total.",
        "solution": "def calculate_total(prices, tax_rate):\n    subtotal = sum(prices)\n    tax = subtotal * tax_rate\n    total = subtotal + tax\n    return round(total, 2)\n",
        "explanation": "This mirrors Python's calculator-style basics: expressions produce values, names store intermediate results, and return gives the final value back to the caller.",
    },
    {
        "id": "make-display-name",
        "topic_id": "python-basics",
        "title": "Make Display Name",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Write `make_display_name(first, last)` that trims extra spaces and returns a title-cased full name. This practices strings, methods, concatenation, and return values.",
        "starter": "def make_display_name(first, last):\n    # clean first and last, then return the display name\n    pass\n",
        "tests": [
            {"label": "basic name", "call": "make_display_name('ada', 'lovelace')", "expected": "Ada Lovelace"},
            {"label": "extra spaces", "call": "make_display_name('  grace ', ' hopper  ')", "expected": "Grace Hopper"},
            {"label": "mixed case", "call": "make_display_name('aLAN', 'tURing')", "expected": "Alan Turing"},
            {"label": "one letter", "call": "make_display_name(' k ', ' d ')", "expected": "K D"},
        ],
        "hint": "Use `strip()` to remove outer spaces and `title()` to normalize words.",
        "solution": "def make_display_name(first, last):\n    clean_first = first.strip().title()\n    clean_last = last.strip().title()\n    return clean_first + ' ' + clean_last\n",
        "explanation": "Strings are immutable, so methods such as strip() and title() return new strings. We store those new values and build the final result.",
    },
    {
        "id": "first-and-last",
        "topic_id": "python-basics",
        "title": "First and Last Items",
        "difficulty": "Beginner",
        "difficulty_order": 3,
        "prompt": "Write `first_and_last(items)` that returns a two-item list containing the first and last values. If the input is empty, return an empty list. This practices lists, indexing, and guarding against IndexError.",
        "starter": "def first_and_last(items):\n    # return [first, last], or [] for an empty list\n    pass\n",
        "tests": [
            {"label": "numbers", "call": "first_and_last([10, 20, 30])", "expected": [10, 30]},
            {"label": "strings", "call": "first_and_last(['api', 'worker'])", "expected": ["api", "worker"]},
            {"label": "single item", "call": "first_and_last(['only'])", "expected": ["only", "only"]},
            {"label": "empty", "call": "first_and_last([])", "expected": []},
        ],
        "hint": "Check for an empty list before using indexes 0 and -1.",
        "solution": "def first_and_last(items):\n    if not items:\n        return []\n    return [items[0], items[-1]]\n",
        "explanation": "Indexing an empty list would raise IndexError. The guard handles that case before we read the first and last positions.",
    },
    {
        "id": "reverse-words",
        "topic_id": "python-basics",
        "title": "Reverse Words",
        "difficulty": "Beginner",
        "difficulty_order": 4,
        "prompt": "Write `reverse_words(text)` that returns the words in reverse order. Extra spaces should not create empty words.",
        "starter": "def reverse_words(text):\n    # return the words in reverse order\n    pass\n",
        "tests": [
            {"label": "simple sentence", "call": "reverse_words('python is fun')", "expected": "fun is python"},
            {"label": "extra spaces", "call": "reverse_words('  hello   world  ')", "expected": "world hello"},
            {"label": "single word", "call": "reverse_words('hello')", "expected": "hello"},
            {"label": "empty string", "call": "reverse_words('')", "expected": ""},
        ],
        "hint": "Use `split()` without arguments, then reverse the list.",
        "solution": "def reverse_words(text):\n    words = text.split()\n    return ' '.join(reversed(words))\n",
        "explanation": "split() without arguments splits on any whitespace and removes empty strings. reversed() gives us the words in reverse order, and join() puts them back together.",
    },
    {
        "id": "even-odd-filter",
        "topic_id": "python-basics",
        "title": "Even/Odd Filter",
        "difficulty": "Beginner",
        "difficulty_order": 5,
        "prompt": "Write `filter_even(numbers)` that returns a list containing only the even numbers from the input list.",
        "starter": "def filter_even(numbers):\n    # return only even numbers\n    pass\n",
        "tests": [
            {"label": "mixed numbers", "call": "filter_even([1, 2, 3, 4, 5, 6])", "expected": [2, 4, 6]},
            {"label": "all odd", "call": "filter_even([1, 3, 5])", "expected": []},
            {"label": "empty list", "call": "filter_even([])", "expected": []},
            {"label": "negatives", "call": "filter_even([-2, -1, 0, 1, 2])", "expected": [-2, 0, 2]},
        ],
        "hint": "A number is even when `number % 2 == 0`.",
        "solution": "def filter_even(numbers):\n    return [n for n in numbers if n % 2 == 0]\n",
        "explanation": "The modulo operator (%) returns the remainder of division. Even numbers have a remainder of 0 when divided by 2. A list comprehension filters them in one line.",
    },
    {
        "id": "count-frequency",
        "topic_id": "data-structures",
        "title": "Count Frequency",
        "difficulty": "Beginner",
        "difficulty_order": 1,
        "prompt": "Write `count_frequency(items)` that returns a dictionary counting how many times each item appears.",
        "starter": "def count_frequency(items):\n    counts = {}\n    # update counts here\n    return counts\n",
        "tests": [
            {"label": "numbers", "call": "count_frequency([1, 2, 1, 3, 2, 1])", "expected": {"1": 3, "2": 2, "3": 1}},
            {"label": "words", "call": "count_frequency(['api', 'ai', 'api'])", "expected": {"api": 2, "ai": 1}},
            {"label": "empty list", "call": "count_frequency([])", "expected": {}},
        ],
        "hint": "Use `str(item)` as the key so numbers and strings behave consistently when sent as JSON.",
        "solution": "def count_frequency(items):\n    counts = {}\n    for item in items:\n        key = str(item)\n        counts[key] = counts.get(key, 0) + 1\n    return counts\n",
        "explanation": "We use str(item) as the key because JSON serialization converts integer keys to strings. The dict.get() method returns a default value (0) when the key doesn't exist yet.",
    },
    {
        "id": "merge-dicts",
        "topic_id": "data-structures",
        "title": "Merge Dictionaries",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Write `merge_dicts(dict_a, dict_b)` that merges two dictionaries. If a key exists in both, use the value from dict_b.",
        "starter": "def merge_dicts(dict_a, dict_b):\n    # merge and return\n    pass\n",
        "tests": [
            {"label": "basic merge", "call": "merge_dicts({'a': 1}, {'b': 2})", "expected": {"a": 1, "b": 2}},
            {"label": "overlap", "call": "merge_dicts({'a': 1, 'b': 2}, {'b': 3})", "expected": {"a": 1, "b": 3}},
            {"label": "empty dicts", "call": "merge_dicts({}, {})", "expected": {}},
        ],
        "hint": "You can use `{**dict_a, **dict_b}` or copy and update.",
        "solution": "def merge_dicts(dict_a, dict_b):\n    result = {**dict_a, **dict_b}\n    return result\n",
        "explanation": "The ** operator unpacks a dictionary. When used in a dict literal, later values override earlier ones for the same key.",
    },
    {
        "id": "valid-email-basic",
        "topic_id": "functions",
        "title": "Basic Email Check",
        "difficulty": "Beginner",
        "difficulty_order": 1,
        "prompt": "Write `is_basic_email(value)` that returns True when the string has exactly one `@` and at least one dot after `@`.",
        "starter": "def is_basic_email(value):\n    pass\n",
        "tests": [
            {"label": "valid", "call": "is_basic_email('dev@example.com')", "expected": True},
            {"label": "missing dot", "call": "is_basic_email('dev@example')", "expected": False},
            {"label": "two ats", "call": "is_basic_email('a@b@example.com')", "expected": False},
            {"label": "empty string", "call": "is_basic_email('')", "expected": False},
        ],
        "hint": "Split once around `@`, then inspect the domain part.",
        "solution": "def is_basic_email(value):\n    if value.count('@') != 1:\n        return False\n    _, domain = value.split('@')\n    return '.' in domain\n",
        "explanation": "count('@') checks for exactly one @. After splitting on @, we check if the domain part contains at least one dot.",
    },
    {
        "id": "clamp-value",
        "topic_id": "functions",
        "title": "Clamp a Value",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Write `clamp(value, low, high)` that returns `value` constrained between `low` and `high` (inclusive).",
        "starter": "def clamp(value, low, high):\n    pass\n",
        "tests": [
            {"label": "in range", "call": "clamp(5, 1, 10)", "expected": 5},
            {"label": "below", "call": "clamp(-3, 0, 100)", "expected": 0},
            {"label": "above", "call": "clamp(150, 0, 100)", "expected": 100},
            {"label": "at boundary", "call": "clamp(10, 10, 10)", "expected": 10},
        ],
        "hint": "Use `max()` and `min()` together.",
        "solution": "def clamp(value, low, high):\n    return max(low, min(value, high))\n",
        "explanation": "min(value, high) ensures the value doesn't exceed the upper bound. max(low, ...) then ensures it doesn't go below the lower bound.",
    },
    {
        "id": "retry-policy",
        "topic_id": "oop",
        "title": "Retry Policy Class",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Create a `RetryPolicy` class. It should accept `max_attempts` and have `should_retry(attempt_number)` returning True if the attempt is below the limit.",
        "starter": "class RetryPolicy:\n    def __init__(self, max_attempts):\n        pass\n\n    def should_retry(self, attempt_number):\n        pass\n",
        "tests": [
            {"label": "retry before limit", "call": "RetryPolicy(3).should_retry(2)", "expected": True},
            {"label": "stop at limit", "call": "RetryPolicy(3).should_retry(3)", "expected": False},
            {"label": "first attempt", "call": "RetryPolicy(1).should_retry(0)", "expected": True},
            {"label": "single attempt exhausted", "call": "RetryPolicy(1).should_retry(1)", "expected": False},
        ],
        "hint": "Store `max_attempts` on `self` and compare the current attempt to it.",
        "solution": "class RetryPolicy:\n    def __init__(self, max_attempts):\n        self.max_attempts = max_attempts\n\n    def should_retry(self, attempt_number):\n        return attempt_number < self.max_attempts\n",
        "explanation": "The __init__ method stores max_attempts as an instance attribute. should_retry compares the current attempt number against the limit.",
    },
    {
        "id": "counter-class",
        "topic_id": "oop",
        "title": "Simple Counter",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Create a `Counter` class with `increment()`, `decrement()`, and `value()` methods. Start at 0.",
        "starter": "class Counter:\n    def __init__(self):\n        pass\n\n    def increment(self):\n        pass\n\n    def decrement(self):\n        pass\n\n    def value(self):\n        pass\n",
        "tests": [
            {"label": "initial value", "call": "Counter().value()", "expected": 0},
            {"label": "increment", "call": "(lambda c: (c.increment(), c.value())[-1])(Counter())", "expected": 1},
            {"label": "decrement", "call": "(lambda c: (c.decrement(), c.value())[-1])(Counter())", "expected": -1},
        ],
        "hint": "Store a count on `self` in __init__ and modify it in each method.",
        "solution": "class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def increment(self):\n        self.count += 1\n\n    def decrement(self):\n        self.count -= 1\n\n    def value(self):\n        return self.count\n",
        "explanation": "Each instance tracks its own count via self.count. Methods modify or read this instance attribute.",
    },
    {
        "id": "safe-int",
        "topic_id": "errors-testing",
        "title": "Safe Integer Parser",
        "difficulty": "Beginner",
        "difficulty_order": 1,
        "prompt": "Write `safe_int(value, default=0)` that converts valid input to int and returns the default for invalid input.",
        "starter": "def safe_int(value, default=0):\n    pass\n",
        "tests": [
            {"label": "number string", "call": "safe_int('42')", "expected": 42},
            {"label": "bad value", "call": "safe_int('nope', default=-1)", "expected": -1},
            {"label": "None input", "call": "safe_int(None, default=0)", "expected": 0},
            {"label": "float string", "call": "safe_int('3.14', default=-1)", "expected": -1},
        ],
        "hint": "Catch `ValueError` and `TypeError` only.",
        "solution": "def safe_int(value, default=0):\n    try:\n        return int(value)\n    except (ValueError, TypeError):\n        return default\n",
        "explanation": "The try/except block catches specific exceptions. ValueError handles invalid strings, TypeError handles None and other non-convertible types.",
    },
    {
        "id": "divide-safely",
        "topic_id": "errors-testing",
        "title": "Safe Division",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Write `safe_divide(a, b)` that returns the result of `a / b`, or `None` if `b` is zero.",
        "starter": "def safe_divide(a, b):\n    pass\n",
        "tests": [
            {"label": "normal division", "call": "safe_divide(10, 2)", "expected": 5.0},
            {"label": "zero divisor", "call": "safe_divide(10, 0)", "expected": None},
            {"label": "zero numerator", "call": "safe_divide(0, 5)", "expected": 0.0},
        ],
        "hint": "Check if `b` is zero before dividing, or catch `ZeroDivisionError`.",
        "solution": "def safe_divide(a, b):\n    if b == 0:\n        return None\n    return a / b\n",
        "explanation": "Checking for zero before dividing is the LBYL (Look Before You Leap) approach. You could also use try/except ZeroDivisionError (EAFP - Easier to Ask Forgiveness).",
    },
    {
        "id": "pydantic-thinking",
        "topic_id": "pydantic",
        "title": "Validate Payload Shape",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Without importing Pydantic, write `validate_ticket(payload)` that returns True if payload has string `title` (non-empty) and integer `priority` from 1 to 5.",
        "starter": "def validate_ticket(payload):\n    pass\n",
        "tests": [
            {"label": "valid", "call": "validate_ticket({'title': 'CPU high', 'priority': 3})", "expected": True},
            {"label": "bad priority", "call": "validate_ticket({'title': 'CPU high', 'priority': 9})", "expected": False},
            {"label": "bad title", "call": "validate_ticket({'title': '', 'priority': 2})", "expected": False},
            {"label": "missing key", "call": "validate_ticket({'priority': 2})", "expected": False},
        ],
        "hint": "Check types first, then business rules.",
        "solution": "def validate_ticket(payload):\n    title = payload.get('title')\n    priority = payload.get('priority')\n    if not isinstance(title, str) or not title:\n        return False\n    if not isinstance(priority, int) or not (1 <= priority <= 5):\n        return False\n    return True\n",
        "explanation": "We use isinstance() for type checking and .get() to safely handle missing keys. Business rules (non-empty, range 1-5) are checked after type validation.",
    },
    {
        "id": "rag-chunks",
        "topic_id": "rag-vectors",
        "title": "Chunk Text",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `chunk_words(text, size)` that splits text into chunks of `size` words.",
        "starter": "def chunk_words(text, size):\n    pass\n",
        "tests": [
            {"label": "even chunks", "call": "chunk_words('a b c d', 2)", "expected": ["a b", "c d"]},
            {"label": "last chunk", "call": "chunk_words('a b c d e', 2)", "expected": ["a b", "c d", "e"]},
            {"label": "single chunk", "call": "chunk_words('hello world', 10)", "expected": ["hello world"]},
            {"label": "empty text", "call": "chunk_words('', 3)", "expected": []},
        ],
        "hint": "Use `range(0, len(words), size)`.",
        "solution": "def chunk_words(text, size):\n    words = text.split()\n    return [' '.join(words[i:i+size]) for i in range(0, len(words), size)]\n",
        "explanation": "split() breaks text into words. range(0, len, size) gives chunk start positions. Slicing words[i:i+size] gets each chunk, and join() reassembles them.",
    },
    {
        "id": "service-health-summary",
        "topic_id": "python-devops",
        "title": "Service Health Summary",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `summarize_health(lines)` that reads lines like `api: ok` or `worker: fail` and returns counts for `ok`, `fail`, and `unknown` statuses.",
        "starter": "def summarize_health(lines):\n    summary = {'ok': 0, 'fail': 0, 'unknown': 0}\n    # parse each line and update the summary\n    return summary\n",
        "tests": [
            {"label": "mixed services", "call": "summarize_health(['api: ok', 'worker: fail', 'db: ok'])", "expected": {"ok": 2, "fail": 1, "unknown": 0}},
            {"label": "unknown status", "call": "summarize_health(['cache: starting', 'api: ok'])", "expected": {"ok": 1, "fail": 0, "unknown": 1}},
            {"label": "bad line", "call": "summarize_health(['api ok', 'db: fail'])", "expected": {"ok": 0, "fail": 1, "unknown": 1}},
            {"label": "empty input", "call": "summarize_health([])", "expected": {"ok": 0, "fail": 0, "unknown": 0}},
        ],
        "hint": "Split on the first colon only. If the line has no colon, count it as `unknown`.",
        "solution": "def summarize_health(lines):\n    summary = {'ok': 0, 'fail': 0, 'unknown': 0}\n    for line in lines:\n        if ':' not in line:\n            summary['unknown'] += 1\n            continue\n        _, status = line.split(':', 1)\n        status = status.strip().lower()\n        if status in ('ok', 'fail'):\n            summary[status] += 1\n        else:\n            summary['unknown'] += 1\n    return summary\n",
        "explanation": "split(':', 1) splits on the first colon only. After getting the status, we normalize it with strip() and lower(), then increment the matching counter.",
    },
    # --- New exercises for previously uncovered topics ---
    {
        "id": "status-code-meaning",
        "topic_id": "fastapi",
        "title": "HTTP Status Code Helper",
        "difficulty": "Beginner",
        "difficulty_order": 1,
        "prompt": "Write `status_meaning(code)` that returns 'success' for 2xx codes, 'redirect' for 3xx, 'client_error' for 4xx, 'server_error' for 5xx, and 'unknown' otherwise.",
        "starter": "def status_meaning(code):\n    pass\n",
        "tests": [
            {"label": "200 OK", "call": "status_meaning(200)", "expected": "success"},
            {"label": "201 Created", "call": "status_meaning(201)", "expected": "success"},
            {"label": "301 Redirect", "call": "status_meaning(301)", "expected": "redirect"},
            {"label": "404 Not Found", "call": "status_meaning(404)", "expected": "client_error"},
            {"label": "500 Server Error", "call": "status_meaning(500)", "expected": "server_error"},
            {"label": "99 Unknown", "call": "status_meaning(99)", "expected": "unknown"},
        ],
        "hint": "Use integer division `code // 100` to get the first digit.",
        "solution": "def status_meaning(code):\n    category = code // 100\n    if category == 2:\n        return 'success'\n    if category == 3:\n        return 'redirect'\n    if category == 4:\n        return 'client_error'\n    if category == 5:\n        return 'server_error'\n    return 'unknown'\n",
        "explanation": "Integer division by 100 gives us the status code category (2, 3, 4, or 5). This is a common pattern for classifying HTTP responses.",
    },
    {
        "id": "parse-query-string",
        "topic_id": "fastapi",
        "title": "Parse Query String",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `parse_query(query)` that takes a query string like `'name=Ada&lang=Python'` and returns a dict like `{'name': 'Ada', 'lang': 'Python'}`. Ignore malformed pairs.",
        "starter": "def parse_query(query):\n    pass\n",
        "tests": [
            {"label": "basic", "call": "parse_query('name=Ada&lang=Python')", "expected": {"name": "Ada", "lang": "Python"}},
            {"label": "single param", "call": "parse_query('page=1')", "expected": {"page": "1"}},
            {"label": "empty string", "call": "parse_query('')", "expected": {}},
            {"label": "malformed pair", "call": "parse_query('good=yes&bad')", "expected": {"good": "yes"}},
        ],
        "hint": "Split on `&` first, then split each pair on `=`.",
        "solution": "def parse_query(query):\n    result = {}\n    if not query:\n        return result\n    for pair in query.split('&'):\n        if '=' in pair:\n            key, value = pair.split('=', 1)\n            result[key] = value\n    return result\n",
        "explanation": "We split the query string on & to get individual pairs, then split each pair on = (max 1 split) to get key and value. Pairs without = are skipped.",
    },
    {
        "id": "async-task-collector",
        "topic_id": "async",
        "title": "Task Result Collector",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `collect_results(tasks)` that takes a list of `{'id': ..., 'status': ...}` dicts and returns a dict grouping task IDs by status.",
        "starter": "def collect_results(tasks):\n    pass\n",
        "tests": [
            {"label": "mixed statuses", "call": "collect_results([{'id': 1, 'status': 'done'}, {'id': 2, 'status': 'fail'}, {'id': 3, 'status': 'done'}])", "expected": {"done": [1, 3], "fail": [2]}},
            {"label": "all same", "call": "collect_results([{'id': 1, 'status': 'ok'}, {'id': 2, 'status': 'ok'}])", "expected": {"ok": [1, 2]}},
            {"label": "empty", "call": "collect_results([])", "expected": {}},
        ],
        "hint": "Use a dictionary where keys are statuses and values are lists of IDs.",
        "solution": "def collect_results(tasks):\n    grouped = {}\n    for task in tasks:\n        status = task['status']\n        if status not in grouped:\n            grouped[status] = []\n        grouped[status].append(task['id'])\n    return grouped\n",
        "explanation": "We iterate through tasks and group their IDs by status. defaultdict(list) would also work, but this exercise practices basic dict operations.",
    },
    {
        "id": "prompt-template",
        "topic_id": "langchain",
        "title": "Simple Prompt Template",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `fill_template(template, variables)` that replaces `{key}` placeholders in a template string with values from a variables dict. Return the filled string.",
        "starter": "def fill_template(template, variables):\n    pass\n",
        "tests": [
            {"label": "basic fill", "call": "fill_template('Hello {name}!', {'name': 'Ada'})", "expected": "Hello Ada!"},
            {"label": "multiple vars", "call": "fill_template('{role}: {task}', {'role': 'assistant', 'task': 'help'})", "expected": "assistant: help"},
            {"label": "no placeholders", "call": "fill_template('plain text', {})", "expected": "plain text"},
        ],
        "hint": "Python's `str.format(**variables)` does exactly this.",
        "solution": "def fill_template(template, variables):\n    return template.format(**variables)\n",
        "explanation": "Python's str.format() with ** unpacking replaces {key} placeholders with values from the dict. This is the core idea behind prompt templates in LLM applications.",
    },
    {
        "id": "state-machine-step",
        "topic_id": "langgraph",
        "title": "Simple State Machine Step",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `next_state(current)` that implements this flow: 'start' → 'classify', 'classify' → 'process', 'process' → 'review', 'review' → 'done'. Return 'unknown' for any other state.",
        "starter": "def next_state(current):\n    pass\n",
        "tests": [
            {"label": "start", "call": "next_state('start')", "expected": "classify"},
            {"label": "classify", "call": "next_state('classify')", "expected": "process"},
            {"label": "process", "call": "next_state('process')", "expected": "review"},
            {"label": "review", "call": "next_state('review')", "expected": "done"},
            {"label": "unknown", "call": "next_state('other')", "expected": "unknown"},
        ],
        "hint": "Use a dictionary to map each state to its successor.",
        "solution": "def next_state(current):\n    transitions = {\n        'start': 'classify',\n        'classify': 'process',\n        'process': 'review',\n        'review': 'done',\n    }\n    return transitions.get(current, 'unknown')\n",
        "explanation": "A dictionary maps each state to the next one. dict.get() with a default value handles unknown states cleanly. This is the core concept behind graph-based workflows.",
    },
    {
        "id": "tool-permission-check",
        "topic_id": "mcp",
        "title": "Tool Permission Checker",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `can_use_tool(tool_name, allowed_tools)` that returns True if the tool is in the allowed list. Tool names should be compared case-insensitively.",
        "starter": "def can_use_tool(tool_name, allowed_tools):\n    pass\n",
        "tests": [
            {"label": "allowed", "call": "can_use_tool('search', ['search', 'read'])", "expected": True},
            {"label": "not allowed", "call": "can_use_tool('delete', ['search', 'read'])", "expected": False},
            {"label": "case insensitive", "call": "can_use_tool('Search', ['search', 'read'])", "expected": True},
            {"label": "empty list", "call": "can_use_tool('search', [])", "expected": False},
        ],
        "hint": "Convert both names to lowercase before comparing.",
        "solution": "def can_use_tool(tool_name, allowed_tools):\n    lower_allowed = {t.lower() for t in allowed_tools}\n    return tool_name.lower() in lower_allowed\n",
        "explanation": "Converting to lowercase ensures case-insensitive comparison. Using a set for allowed_tools gives O(1) lookup, which matters when the permission list grows.",
    },
    {
        "id": "sql-where-builder",
        "topic_id": "sql-http-git",
        "title": "SQL WHERE Clause Builder",
        "difficulty": "Intermediate",
        "difficulty_order": 1,
        "prompt": "Write `build_where(filters)` that takes a dict like `{'name': 'Ada', 'active': True}` and returns a SQL WHERE string like `\"name = 'Ada' AND active = True\"`. Return empty string for empty dict.",
        "starter": "def build_where(filters):\n    pass\n",
        "tests": [
            {"label": "single filter", "call": "build_where({'name': 'Ada'})", "expected": "name = 'Ada'"},
            {"label": "multiple filters", "call": "build_where({'active': True, 'role': 'admin'})", "expected": "active = True AND role = 'admin'"},
            {"label": "empty filters", "call": "build_where({})", "expected": ""},
        ],
        "hint": "Build each condition as `key = value`, quoting strings. Join with ' AND '.",
        "solution": "def build_where(filters):\n    parts = []\n    for key, value in filters.items():\n        if isinstance(value, str):\n            parts.append(f\"{key} = '{value}'\")\n        else:\n            parts.append(f\"{key} = {value}\")\n    return ' AND '.join(parts)\n",
        "explanation": "We format each filter as a SQL condition, quoting string values. This is a simplified builder — real SQL should use parameterized queries to prevent injection.",
    },
    {
        "id": "normalize-priority",
        "topic_id": "pydantic",
        "title": "Normalize Priority Field",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `normalize_priority(value)` that converts a priority to an integer 1–5.\n\nRules:\n- Strings: `'high'` → 1, `'medium'` → 3, `'low'` → 5 (case-insensitive)\n- Integers already in range 1–5 → return as-is\n- Anything else → return `None`",
        "starter": "def normalize_priority(value):\n    # Handle string labels and int values\n    pass\n",
        "tests": [
            {"label": "string high", "call": "normalize_priority('high')", "expected": 1},
            {"label": "string HIGH uppercase", "call": "normalize_priority('HIGH')", "expected": 1},
            {"label": "string medium", "call": "normalize_priority('medium')", "expected": 3},
            {"label": "string low", "call": "normalize_priority('low')", "expected": 5},
            {"label": "int in range", "call": "normalize_priority(2)", "expected": 2},
            {"label": "int out of range", "call": "normalize_priority(9)", "expected": None},
            {"label": "unknown string", "call": "normalize_priority('urgent')", "expected": None},
        ],
        "hint": "Use a dict for string→int mapping. Check isinstance for int, and validate the range.",
        "solution": "def normalize_priority(value):\n    mapping = {'high': 1, 'medium': 3, 'low': 5}\n    if isinstance(value, str):\n        return mapping.get(value.lower())\n    if isinstance(value, int) and 1 <= value <= 5:\n        return value\n    return None\n",
        "explanation": "This is a boundary normalizer — exactly the kind of coercion a Pydantic validator would run. It handles string labels, integer values, and rejects invalid inputs with None instead of raising.",
    },
    {
        "id": "backoff-delay",
        "topic_id": "async",
        "title": "Exponential Backoff Calculator",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `backoff_delay(attempt, base=1.0, max_delay=30.0)` that returns the retry wait time in seconds.\n\nFormula: `min(base * 2^attempt, max_delay)`\n\nThis is the classic exponential backoff used in async retry logic.",
        "starter": "def backoff_delay(attempt, base=1.0, max_delay=30.0):\n    pass\n",
        "tests": [
            {"label": "attempt 0", "call": "backoff_delay(0)", "expected": 1.0},
            {"label": "attempt 1", "call": "backoff_delay(1)", "expected": 2.0},
            {"label": "attempt 3", "call": "backoff_delay(3)", "expected": 8.0},
            {"label": "capped at max_delay", "call": "backoff_delay(10)", "expected": 30.0},
            {"label": "custom base", "call": "backoff_delay(2, base=0.5)", "expected": 2.0},
            {"label": "custom max", "call": "backoff_delay(4, max_delay=10.0)", "expected": 10.0},
        ],
        "hint": "Use `min()` with the formula and `max_delay`. `2 ** attempt` gives powers of two.",
        "solution": "def backoff_delay(attempt, base=1.0, max_delay=30.0):\n    return min(base * (2 ** attempt), max_delay)\n",
        "explanation": "Exponential backoff doubles the wait each retry to avoid overwhelming a recovering service. The cap prevents indefinitely long waits. This is used in httpx, aiohttp retry libraries, and cloud SDK clients.",
    },
    {
        "id": "extract-kv-pairs",
        "topic_id": "langchain",
        "title": "Extract Key-Value Pairs",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `extract_kv_pairs(text)` that parses `key: value` lines from a string and returns a dict.\n\nRules:\n- One pair per line, separated by `: ` (colon-space)\n- Ignore lines without `: `\n- Strip whitespace from keys and values",
        "starter": "def extract_kv_pairs(text):\n    result = {}\n    # parse each line\n    return result\n",
        "tests": [
            {"label": "single pair", "call": "extract_kv_pairs('name: Ada')", "expected": {"name": "Ada"}},
            {"label": "multiple pairs", "call": "extract_kv_pairs('role: engineer\\nteam: ai')", "expected": {"role": "engineer", "team": "ai"}},
            {"label": "skip blank lines", "call": "extract_kv_pairs('a: 1\\n\\nb: 2')", "expected": {"a": "1", "b": "2"}},
            {"label": "skip lines without separator", "call": "extract_kv_pairs('no separator\\nkey: val')", "expected": {"key": "val"}},
            {"label": "strip whitespace", "call": "extract_kv_pairs('  city :  London  ')", "expected": {"city": "London"}},
            {"label": "empty text", "call": "extract_kv_pairs('')", "expected": {}},
        ],
        "hint": "Iterate over `text.splitlines()`. Use `': ' in line` to check, then `split(': ', 1)` to split.",
        "solution": "def extract_kv_pairs(text):\n    result = {}\n    for line in text.splitlines():\n        if ': ' in line:\n            key, value = line.split(': ', 1)\n            result[key.strip()] = value.strip()\n    return result\n",
        "explanation": "Output parsers in LangChain often need to extract structured data from model text. This is a simplified version of that pattern: split on a known delimiter, build a dict from key-value pairs.",
    },
    {
        "id": "merge-graph-state",
        "topic_id": "langgraph",
        "title": "Merge Graph State",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `merge_state(state, updates)` that merges updates into state.\n\nRules:\n- List fields: **extend** (append new items to existing list)\n- All other fields: **overwrite**\n- Fields in updates that don't exist in state get added",
        "starter": "def merge_state(state, updates):\n    result = dict(state)\n    # merge updates into result\n    return result\n",
        "tests": [
            {"label": "overwrite scalar", "call": "merge_state({'status': 'start'}, {'status': 'done'})", "expected": {"status": "done"}},
            {"label": "extend list", "call": "merge_state({'msgs': ['a']}, {'msgs': ['b']})", "expected": {"msgs": ["a", "b"]}},
            {"label": "add new key", "call": "merge_state({'x': 1}, {'y': 2})", "expected": {"x": 1, "y": 2}},
            {"label": "mixed update", "call": "merge_state({'step': 1, 'log': ['init']}, {'step': 2, 'log': ['run']})", "expected": {"step": 2, "log": ["init", "run"]}},
            {"label": "empty updates", "call": "merge_state({'a': 1}, {})", "expected": {"a": 1}},
        ],
        "hint": "Check `isinstance(value, list) and isinstance(result.get(key), list)` to decide whether to extend or overwrite.",
        "solution": "def merge_state(state, updates):\n    result = dict(state)\n    for key, value in updates.items():\n        if isinstance(value, list) and isinstance(result.get(key), list):\n            result[key] = result[key] + value\n        else:\n            result[key] = value\n    return result\n",
        "explanation": "In LangGraph, each node returns partial state updates. List fields accumulate messages and logs across nodes, while scalar fields like 'status' or 'step' are replaced. This reducer pattern is central to how LangGraph manages shared state.",
    },
    {
        "id": "validate-tool-args",
        "topic_id": "mcp",
        "title": "Validate Tool Arguments",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `validate_tool_args(call, schema)` that checks whether a tool call includes all required arguments.\n\n- `call` is a dict with an `'args'` key (also a dict)\n- `schema` has a `'required'` key listing required argument names\n- Return `True` if all required args are present, `False` otherwise",
        "starter": "def validate_tool_args(call, schema):\n    pass\n",
        "tests": [
            {"label": "all required present", "call": "validate_tool_args({'args': {'query': 'py', 'limit': 5}}, {'required': ['query']})", "expected": True},
            {"label": "missing required", "call": "validate_tool_args({'args': {'limit': 5}}, {'required': ['query', 'limit']})", "expected": False},
            {"label": "no required fields", "call": "validate_tool_args({'args': {}}, {'required': []})", "expected": True},
            {"label": "empty args dict", "call": "validate_tool_args({'args': {}}, {'required': ['query']})", "expected": False},
            {"label": "extra args are fine", "call": "validate_tool_args({'args': {'a': 1, 'b': 2}}, {'required': ['a']})", "expected": True},
        ],
        "hint": "Use `all(k in call['args'] for k in schema['required'])`.",
        "solution": "def validate_tool_args(call, schema):\n    required = schema.get('required', [])\n    args = call.get('args', {})\n    return all(k in args for k in required)\n",
        "explanation": "MCP servers should validate that a tool call has all required arguments before executing. The `all()` + generator pattern is idiomatic Python for checking all conditions hold simultaneously.",
    },
    {
        "id": "filter-docs-by-metadata",
        "topic_id": "rag-vectors",
        "title": "Filter Documents by Metadata",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `filter_docs(docs, filters)` that returns only the documents where **all** filter key-value pairs match the document's metadata.\n\n- `docs` is a list of dicts\n- `filters` is a dict of required field values\n- Return empty list if filters is empty",
        "starter": "def filter_docs(docs, filters):\n    pass\n",
        "tests": [
            {"label": "single filter match", "call": "filter_docs([{'topic': 'ml', 'year': 2024}, {'topic': 'devops', 'year': 2023}], {'topic': 'ml'})", "expected": [{"topic": "ml", "year": 2024}]},
            {"label": "multi filter match", "call": "filter_docs([{'topic': 'ml', 'year': 2024}, {'topic': 'ml', 'year': 2023}], {'topic': 'ml', 'year': 2024})", "expected": [{"topic": "ml", "year": 2024}]},
            {"label": "no match", "call": "filter_docs([{'topic': 'devops'}], {'topic': 'ml'})", "expected": []},
            {"label": "empty filters returns empty", "call": "filter_docs([{'topic': 'ml'}], {})", "expected": []},
            {"label": "empty docs", "call": "filter_docs([], {'topic': 'ml'})", "expected": []},
        ],
        "hint": "Use `all(doc.get(k) == v for k, v in filters.items())`. Guard against empty filters first.",
        "solution": "def filter_docs(docs, filters):\n    if not filters:\n        return []\n    return [doc for doc in docs if all(doc.get(k) == v for k, v in filters.items())]\n",
        "explanation": "Metadata filtering is a core RAG optimization: restrict retrieval to a specific product, date, or topic. The all() check ensures every filter condition must match before a doc is included.",
    },
    {
        "id": "parse-env-file",
        "topic_id": "python-devops",
        "title": "Parse .env File",
        "difficulty": "Intermediate",
        "difficulty_order": 2,
        "prompt": "Write `parse_env_file(text)` that parses a `.env` file string into a dict.\n\nRules:\n- Lines starting with `#` are comments — skip them\n- Blank lines — skip\n- Each valid line has the format `KEY=VALUE`\n- Strip whitespace from both key and value",
        "starter": "def parse_env_file(text):\n    result = {}\n    # parse lines\n    return result\n",
        "tests": [
            {"label": "simple pair", "call": "parse_env_file('HOST=localhost')", "expected": {"HOST": "localhost"}},
            {"label": "skip comment", "call": "parse_env_file('# comment\\nPORT=8080')", "expected": {"PORT": "8080"}},
            {"label": "skip blank line", "call": "parse_env_file('A=1\\n\\nB=2')", "expected": {"A": "1", "B": "2"}},
            {"label": "strip whitespace", "call": "parse_env_file('  DB = postgres  ')", "expected": {"DB": "postgres"}},
            {"label": "value with equals sign", "call": "parse_env_file('URL=http://a.com?x=1')", "expected": {"URL": "http://a.com?x=1"}},
            {"label": "empty text", "call": "parse_env_file('')", "expected": {}},
        ],
        "hint": "Use `split('=', 1)` to split at the first `=` only, so values can contain `=`.",
        "solution": "def parse_env_file(text):\n    result = {}\n    for line in text.splitlines():\n        line = line.strip()\n        if not line or line.startswith('#'):\n            continue\n        if '=' in line:\n            key, value = line.split('=', 1)\n            result[key.strip()] = value.strip()\n    return result\n",
        "explanation": "DevOps scripts often read .env files to load configuration. split('=', 1) splits only at the first equals sign so URLs and connection strings with = in the value are preserved correctly.",
    },
    {
        "id": "parse-http-status",
        "topic_id": "sql-http-git",
        "title": "Parse HTTP Status Line",
        "difficulty": "Beginner",
        "difficulty_order": 2,
        "prompt": "Write `parse_status_line(line)` that parses an HTTP status line like `'HTTP/1.1 200 OK'` and returns a dict with keys `version`, `code` (int), and `reason` (str).",
        "starter": "def parse_status_line(line):\n    # Split the status line into its three parts\n    pass\n",
        "tests": [
            {"label": "200 OK", "call": "parse_status_line('HTTP/1.1 200 OK')", "expected": {"version": "HTTP/1.1", "code": 200, "reason": "OK"}},
            {"label": "404 Not Found", "call": "parse_status_line('HTTP/1.1 404 Not Found')", "expected": {"version": "HTTP/1.1", "code": 404, "reason": "Not Found"}},
            {"label": "201 Created", "call": "parse_status_line('HTTP/1.1 201 Created')", "expected": {"version": "HTTP/1.1", "code": 201, "reason": "Created"}},
            {"label": "500 Internal Server Error", "call": "parse_status_line('HTTP/1.1 500 Internal Server Error')", "expected": {"version": "HTTP/1.1", "code": 500, "reason": "Internal Server Error"}},
        ],
        "hint": "Use `split(' ', 2)` to split into exactly 3 parts. Convert the middle part to int.",
        "solution": "def parse_status_line(line):\n    parts = line.split(' ', 2)\n    return {'version': parts[0], 'code': int(parts[1]), 'reason': parts[2]}\n",
        "explanation": "HTTP status lines always have three parts: protocol version, numeric code, and human-readable reason. split(' ', 2) limits to 2 splits so multi-word reasons like 'Not Found' stay together.",
    },
]
